language: node_js

sudo: false
dist: trusty

addons:
  chrome: stable

node_js:
  - "7.4.*"

branches:
  only:
    - master
    - dev

after_success:
  npm run coveralls

sudo: false

notifications:
  email: false
